title: My Life in Waves
author: Andy Dixon
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am not sure what to write here as it is just a learning task. I really think that it is very windy today. Cormac is coming to visit this weekend.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
